# Generated by Django 4.2.11 on 2024-03-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_seller_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
