# Generated by Django 4.2.11 on 2024-03-24 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_product_seller'),
        ('seller', '0005_remove_seller_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='product',
            field=models.ManyToManyField(null=True, to='products.product'),
        ),
    ]
