# Generated by Django 4.2.11 on 2024-03-25 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0008_rename_seller_seller_product_sellers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller_Product',
        ),
    ]
