# Generated by Django 5.0.3 on 2024-03-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='product',
            name='IMAGE',
            field=models.ImageField(default='', upload_to='products/images/'),
            preserve_default=False,
        ),
    ]
