# Generated by Django 5.0.3 on 2024-03-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_thumbnail_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discountPercentage',
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
